// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthLyn9O7s9Q0UsHn3Vm0xoIyvYZ4YMpI',
    appId: '1:184891157747:web:f5995b05e4526ab5539b86',
    messagingSenderId: '184891157747',
    projectId: 'aquality-75b54',
    authDomain: 'aquality-75b54.firebaseapp.com',
    storageBucket: 'aquality-75b54.firebasestorage.app',
    measurementId: 'G-ZGLTVLHX99',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthLyn9O7s9Q0UsHn3Vm0xoIyvYZ4YMpI',
    appId: '1:184891157747:web:e79b0813f99050bb539b86',
    messagingSenderId: '184891157747',
    projectId: 'aquality-75b54',
    authDomain: 'aquality-75b54.firebaseapp.com',
    storageBucket: 'aquality-75b54.firebasestorage.app',
    measurementId: 'G-4RMSJRWF0Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGYHPeuFSrLwNKb4IWmMNKKuG2dX4I90',
    appId: '1:184891157747:ios:f758092052d21263539b86',
    messagingSenderId: '184891157747',
    projectId: 'aquality-75b54',
    storageBucket: 'aquality-75b54.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGYHPeuFSrLwNKb4IWmMNKKuG2dX4I90',
    appId: '1:184891157747:ios:f758092052d21263539b86',
    messagingSenderId: '184891157747',
    projectId: 'aquality-75b54',
    storageBucket: 'aquality-75b54.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Umyl_DBC__SdAYWpSNqiN5pqF6Mb514',
    appId: '1:184891157747:android:bd8a5590170ae195539b86',
    messagingSenderId: '184891157747',
    projectId: 'aquality-75b54',
    storageBucket: 'aquality-75b54.firebasestorage.app',
  );

}